sudo: false
language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
addons:
  apt:
    packages:
    - exuberant-ctags
install:
  - "pip install ."
  - "pip install -r test_requirements.txt"
script:
  - git config --global user.email "you@example.com"
  - git config --global user.name "Your Name"
  - ./runtests.sh
